"""Objetos de domínio independentes de UI, transporte e banco de dados."""

from app.domain.admin import (
    AdminAuthentication,
    AdminCredentials,
    Administrator,
    DashboardAlertCategories,
    DashboardAlertStatus,
    DashboardAlertTrendPoint,
    DashboardSummary,
)
from app.domain.alerts import (
    AdminAlert,
    AdminAlertPage,
    AlertActor,
    AlertCamera,
    AlertEmployee,
    AlertOccurrence,
    AlertOperationalContext,
    AlertSector,
)
from app.domain.operations import (
    CameraDraft,
    CameraOption,
    NormalizedPoint,
    OperationCatalog,
    OperationConfiguration,
    OperationDraft,
    PolygonGeometry,
    PpeOption,
    RiskArea,
    RiskAreaDraft,
    SectorOption,
)
from app.domain.realtime import (
    ConnectionReadyEvent,
    HeartbeatEvent,
    RealtimeAlert,
    RealtimeEvent,
)

__all__ = [
    "AdminAlert",
    "AdminAlertPage",
    "AdminAuthentication",
    "AdminCredentials",
    "Administrator",
    "DashboardSummary",
    "DashboardAlertCategories",
    "DashboardAlertStatus",
    "DashboardAlertTrendPoint",
    "ConnectionReadyEvent",
    "CameraDraft",
    "CameraOption",
    "HeartbeatEvent",
    "NormalizedPoint",
    "OperationCatalog",
    "OperationConfiguration",
    "OperationDraft",
    "PolygonGeometry",
    "PpeOption",
    "RealtimeAlert",
    "RealtimeEvent",
    "RiskArea",
    "RiskAreaDraft",
    "SectorOption",
    "AlertActor",
    "AlertCamera",
    "AlertEmployee",
    "AlertOccurrence",
    "AlertOperationalContext",
    "AlertSector",
]
