"""Adicionar atualizado_em em usuarios

Revision ID: 441c04c14c57
Revises: d5338781e8f0
Create Date: 2026-08-20 02:33:14.844592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '441c04c14c57'
down_revision: Union[str, Sequence[str], None] = 'd5338781e8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('usuarios', 'criado_em',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'criado_em',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('usuarios', 'atualizado_em')
    # ### end Alembic commands ###
