"""Criar tabela de usuarios

Revision ID: d5338781e8f0
Revises: 42d54200970a
Create Date: 2026-08-20 02:26:27.049895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5338781e8f0'
down_revision: Union[str, Sequence[str], None] = '42d54200970a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_column('usuarios', 'atualizado_em')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('atualizado_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.alter_column('usuarios', 'criado_em',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
